version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./db-scripts/create-extensions-db.sh:/docker-entrypoint-initdb.d/create-extensions-db.sh
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker-db.env
