version: "3"
services:
  pokemon:
    container_name: pokemon
    build:
      context: ../
      args:
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
    ports:
      - "3000:3000"
    env_file:
      - docker-app.env
